In [29]:
import pandas as pd
import numpy as np

In [30]:
#importing datasets
df = pd.read_csv("./final_dataset.csv")
df.head()

,season,year,month,holiday,weekday,workingday,weathersit,temp,hum,windspeed,rentals
0,1,0,1,0,6,0,2,0.344167,0.805833,0.160446,985
1,1,0,1,0,0,0,2,0.363478,0.696087,0.248539,801
2,1,0,1,0,1,1,1,0.196364,0.437273,0.248309,1349
3,1,0,1,0,2,1,1,0.200000,0.590435,0.160296,1562
4,1,0,1,0,3,1,1,0.226957,0.436957,0.186900,1600

In [31]:
df.columns

Index(['season', 'year', 'month', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'hum', 'windspeed', 'rentals'],
      dtype='str')

In [32]:
df.describe()

,season,year,month,holiday,weekday,workingday,weathersit,temp,hum,windspeed,rentals
count,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
mean,2.496580,0.500684,6.519836,0.028728,2.997264,0.683995,1.395349,0.495385,0.627894,0.190486,4504.348837
std,1.110807,0.500342,3.451913,0.167155,2.004787,0.465233,0.544894,0.183051,0.142429,0.077498,1937.211452
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.059130,0.000000,0.022392,22.000000
25%,2.000000,0.000000,4.000000,0.000000,1.000000,0.000000,1.000000,0.337083,0.520000,0.134950,3152.000000
50%,3.000000,1.000000,7.000000,0.000000,3.000000,1.000000,1.000000,0.498333,0.626667,0.180975,4548.000000
75%,3.000000,1.000000,10.000000,0.000000,5.000000,1.000000,2.000000,0.655417,0.730209,0.233214,5956.000000
max,4.000000,1.000000,12.000000,1.000000,6.000000,1.000000,3.000000,0.861667,0.972500,0.507463,8714.000000

In [33]:
df.isnull().sum()

season        0
year          0
month         0
holiday       0
weekday       0
workingday    0
weathersit    0
temp          0
hum           0
windspeed     0
rentals       0
dtype: int64

In [34]:
df_clean=df.copy()

In [35]:
df_clean = df.copy()

df_clean.drop(
    columns=["instant","dteday","casual","registered","atemp"],
    errors="ignore",
    inplace=True
)

In [36]:
df_clean.duplicated().sum()

np.int64(0)

In [37]:
categorical_cols = [
    "season", "yr", "mnth",
    "holiday", "workingday", "weathersit"
]
categorical_cols = ["season","year","month","holiday","workingday","weathersit"]

existing_cols = [c for c in categorical_cols if c in df_clean.columns]

df_clean[existing_cols] = df_clean[existing_cols].astype("category")

In [38]:
df_clean.rename(columns={"cnt":"rentals","mnth":"month","yr":"year"},inplace=True)

In [39]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   season      731 non-null    category
 1   year        731 non-null    category
 2   month       731 non-null    category
 3   holiday     731 non-null    category
 4   weekday     731 non-null    int64
 5   workingday  731 non-null    category
 6   weathersit  731 non-null    category
 7   temp        731 non-null    float64
 8   hum         731 non-null    float64
 9   windspeed   731 non-null    float64
 10  rentals     731 non-null    int64
dtypes: category(6), float64(3), int64(2)
memory usage: 33.2 KB

In [40]:
df_clean.head()

,season,year,month,holiday,weekday,workingday,weathersit,temp,hum,windspeed,rentals
0,1,0,1,0,6,0,2,0.344167,0.805833,0.160446,985
1,1,0,1,0,0,0,2,0.363478,0.696087,0.248539,801
2,1,0,1,0,1,1,1,0.196364,0.437273,0.248309,1349
3,1,0,1,0,2,1,1,0.200000,0.590435,0.160296,1562
4,1,0,1,0,3,1,1,0.226957,0.436957,0.186900,1600

In [41]:
print(df_clean['rentals'].max())
print(df_clean['temp'].mean())
print(df_clean['hum'].min())

8714
0.495384788508892
0.0

In [42]:
working_days = df_clean[df_clean['workingday'] == 1]
working_days.head()

,season,year,month,holiday,weekday,workingday,weathersit,temp,hum,windspeed,rentals
2,1,0,1,0,1,1,1,0.196364,0.437273,0.248309,1349
3,1,0,1,0,2,1,1,0.200000,0.590435,0.160296,1562
4,1,0,1,0,3,1,1,0.226957,0.436957,0.186900,1600
5,1,0,1,0,4,1,1,0.204348,0.518261,0.089565,1606
6,1,0,1,0,5,1,2,0.196522,0.498696,0.168726,1510

In [43]:
df_clean.groupby('season')['rentals'].mean()

season
1    2604.132597
2    4992.331522
3    5644.303191
4    4728.162921
Name: rentals, dtype: float64

In [44]:
df_clean.groupby('workingday')['rentals'].mean()

workingday
0    4330.168831
1    4584.820000
Name: rentals, dtype: float64

In [45]:
df_clean.to_csv('final_dataset.csv', index=False)